### ISSUE TITLE
Slack Registration

### ISSUE THREAD

**Issue by colliermc** [VATSIM-UK/core#1016]
There appears to be an issue with Slack registration. Slackbot is messaging users telling them to link their accounts on Core. When this is attempted, Core gives an error and tells the user to submit a ticket to web services.

**Comment by NFarrington** [comment]
This appears to only have affected one user (WEB-508524) - have there been any others?

This will generally only occur for users who have an expired token, and for those with no token who have already been invited to Slack, and this does require manual intervention from Web Services the way it is currently written.

**Comment by CalumTowers** [comment]
Probably my fault. I've seen a lot of Slack related things coming through HD probably not related.
