### ISSUE TITLE
Non-UK Group Membership Options

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#1054]
## Error in VATSIM-UK/Core (Laravel)

**App\Exceptions\Community\Membership\MustBeADivisionMemberException** in **POST /community/membership/deploy**
It is not possible to join a UK Community Group unless you are a UK member.

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/5a3a7b7e0f7e8b001a63d358?event_id=5a3a7b9f82dda60018f46473&i=gh&m=ci)

## Stacktrace

    app/Models/Mship/Concerns/HasCommunityGroups.php:52 - App\Models\Mship\Account::guardAgainstNonDivisionJoiningACommunityGroup
    app/Models/Mship/Concerns/HasCommunityGroups.php:31 - App\Models\Mship\Account::addCommunityGroup
    app/Http/Controllers/Community/Membership.php:30 - App\Http\Controllers\Community\Membership::postDeploy
    app/Http/Controllers/BaseController.php:38 - App\Http\Controllers\BaseController::App\Http\Controllers\{closure}
    app/Http/Middleware/RedirectToIntended.php:23 - App\Http\Middleware\RedirectToIntended::handle
    app/Traits/Middleware/RedirectsOnFailure.php:40 - App\Http\Middleware\MustHaveCommunityGroup::handle
    app/Traits/Middleware/RedirectsOnFailure.php:48 - App\Http\Middleware\UserMustReadNotifications::handle
    app/Http/Middleware/DenyIfBanned.php:27 - App\Http\Middleware\DenyIfBanned::handle
    app/Traits/Middleware/RedirectsOnFailure.php:48 - App\Http\Middleware\MandatoryPasswords::handle
    app/Http/Middleware/RecordLoginInfo.php:39 - App\Http\Middleware\RecordLoginInfo::handle
    app/Http/Middleware/TrackInactivity.php:43 - App\Http\Middleware\TrackInactivity::handle

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/5a3a7b7e0f7e8b001a63d358?event_id=5a3a7b9f82dda60018f46473&i=gh&m=ci)

*Created by Neil Farrington via Bugsnag*

**Comment by NFarrington** [comment]
This error occurs correctly, however members on the dashboard should not be presented with the option to join a group in the first place.

`App\Policies\MembershipPolicy::deploy()` needs adjusting.
