### ISSUE TITLE
Increase TeamSpeak registration limit

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#1129]
https://github.com/VATSIM-UK/core/blob/development/app/Http/Controllers/TeamSpeak/Registration.php

Increase to 5

**Comment by NFarrington** [comment]
Is there any need to keep the registration limit at all?

**Comment by NFarrington** [comment]
I've increased it to 25, so there's still some sort of sane limit (no one should ever have or need 25).
