### ISSUE TITLE
Visiting Controllers List

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#1130]
Ability to...

- Mark a member as visiting the UK
- Note what positions they can control on (free text)
- Trigger email when added to list

Edit...
- Remove visiting status of member
- Change which positions they can control on
- Trigger email to update member

List all controllers on publicly accessible link along with their CID, controlling rating, home div and positions can be controlled.

**Comment by NFarrington** [comment]
"Trigger email to update member" - can you expand on this? Update member on/with what specifically?
