### ISSUE TITLE
Feedback forms with no contact cause error on summary email

### ISSUE THREAD

**Issue by atoff** [VATSIM-UK/core#1145]
When a feedback form doesn't have a contact assigned, the summary email job errors.

Either force feedback forms to have a contact assigned, or alter logic in job.

**Comment by NFarrington** [comment]
There may be a future use case where a specific form shouldn't have any summary emails sent - therefore, if no contact is assigned, a summary email will not be generated or sent.

Duplicate of #1127 - closing #1127.
