### ISSUE TITLE
/api/user Exception

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#1554]
ErrorException in GET /api/userCreating default object from empty value

Http/Middleware/ApiTracking.php:37 - Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
    Http/Middleware/ApiTracking.php:37 - App\Http\Middleware\ApiTracking::terminate

Need to handle exception better in ApiTracking.php

**Comment by vatsim-uk-pa** [comment]
This issue has been linked to an error in Bugsnag
[**ErrorException** in **GET /api/user**](https://app.bugsnag.com/vatsim-uk/core/errors/5d5f523dc234880019b943a8?event_id=5e3748ac0055edbf07d20000&i=gh&m=li)
