### ISSUE TITLE
Migrate Crons To Scheduler

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#1558]
Time Expression | Human Form | Command
-- | -- | --
0 22 * * * | At every 22nd Hour | feedback:summarise --interval=p1d
30 23 * * * | At 23:30 | Sync:Helpdesk
0 23 * * * | At 23:00 | Sync:Mentors
1 0 * * * | At 00:01 | Sync:Community
1 0 * * * | At 00:01 | Sync:RTS
1 0 * * * | At 00:01 | Sync:Moodle
0 2,14 * * * | At 02:00 and 14:00 | Members:CertImport --full
30 */2 * * * | At 30 minutes past every 2 hours | Members:CertImport
45 0 * * * | At 00:45 | Members:CertUpdate --type=daily 5000
15 1 * * 1 | At 01:15 every Monday | Members:CertUpdate --type=weekly 5000
45 1 1 * * | At 01:45 on the 1st of the Month | Members:CertUpdate --type=monthly 5000
45 */2 * * * | At 45 minutes past every 2nd hour. | Members:CertUpdate --type=all 100
/* * * * * | Every Minute | visit-transfer:cleanup
/* * * * * | Every Minute | teaman:runner -v
*/2 * * * * | Every 2nd Minute | networkdata:download
0 * * * * | Every Hour | slack:manager
1 0 * * * | At 00:01 | sys:statistics:daily
30 0 * * * | At 00:30 | visittransfer:statistics:daily

**Comment by AxonC** [comment]
# Active Commands
Time Expression | Human Form | Command
-- | -- | --
0 22 * * * | At every 22nd Hour | feedback:summarise --interval=p1d
30 23 * * * | At 23:30 | Sync:Helpdesk
1 0 * * * | At 00:01 | Sync:Community
0 2,14 * * * | At 02:00 and 14:00 | Members:CertImport --full
30 */2 * * * | At 30 minutes past every 2 hours | Members:CertImport
45 0 * * * | At 00:45 | Members:CertUpdate --type=daily 5000
15 1 * * 1 | At 01:15 every Monday | Members:CertUpdate --type=weekly 5000
45 1 1 * * | At 01:45 on the 1st of the Month | Members:CertUpdate --type=monthly 5000
45 */2 * * * | At 45 minutes past every 2nd hour. | Members:CertUpdate --type=all 100
/* * * * * | Every Minute | visit-transfer:cleanup
/* * * * * | Every Minute | teaman:runner -v
*/2 * * * * | Every 2nd Minute | networkdata:download
0 * * * * | Every Hour | slack:manager
1 0 * * * | At 00:01 | sys:statistics:daily
30 0 * * * | At 00:30 | visittransfer:statistics:daily

# Deprecated Commands
Time Expression | Human Form | Command
-- | -- | --
1 0 * * * | At 00:01 | Sync:RTS
0 23 * * * | At 23:00 | Sync:Mentors
1 0 * * * | At 00:01 | Sync:Moodle

/cc @CalumTowers @atoff
