### ISSUE TITLE
As a user, I can easily find guide links on the dashboard

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#1564]
Add in guide links for:

- Teamspeak
- Slack
- UKCP

Ensuring that the purpose of each button is clear.

**Comment by aaronholtomcook** [comment]
@CalumTowers  if you can provide me the links i'll add them to the dashboard

**Comment by CalumTowers** [comment]
@aaronholtomcook At present;

https://www.vatsim.uk/community/teamspeak - has a guide for TeamSpeak
https://www.vatsim.uk/mship/manage/slack/new - is the closest thing to a guide for Slack
https://www.vatsim.uk/ukcp/ - has a guide for UKCP

Probably needs some changes to content / page structure.

**Comment by aaronholtomcook** [comment]
Suggest we don't show the slack guide if they have a linked slack account, as the link goes to dashboard @CalumTowers
