### ISSUE TITLE
Duplicate Notification Acknowledgement

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#1572]
## Error in Core

**Illuminate\Database\QueryException** in **POST /mship/notification/acknowledge/6**
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '6-1218620' for key 'sys_notification_read_notification_id_account_id_unique' (SQL: insert into `sys_notification_read` (`account_id`, `created_at`, `notification_id`) values (1218620, 2019-10-18 15:19:01, 6))

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/core/errors/5d5b096a83cd290019c71c12?event_id=5da9d7e6005110868d180000&i=gh&m=ci)

## Stacktrace

    Http/Controllers/Mship/Notification.php:20 - App\Http\Controllers\Mship\Notification::postAcknowledge
    Http/Controllers/BaseController.php:40 - App\Http\Controllers\BaseController::App\Http\Controllers\{closure}
    Http/Middleware/RedirectToIntended.php:23 - App\Http\Middleware\RedirectToIntended::handle
    Traits/Middleware/RedirectsOnFailure.php:28 - App\Http\Middleware\MustHaveCommunityGroup::handle
    Traits/Middleware/RedirectsOnFailure.php:33 - App\Http\Middleware\UserMustReadNotifications::handle
    Http/Middleware/DenyIfBanned.php:27 - App\Http\Middleware\DenyIfBanned::handle
    Traits/Middleware/RedirectsOnFailure.php:28 - App\Http\Middleware\MandatoryPasswords::handle
    Http/Middleware/RecordLoginInfo.php:39 - App\Http\Middleware\RecordLoginInfo::handle
    Http/Middleware/TrackInactivity.php:43 - App\Http\Middleware\TrackInactivity::handle

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/core/errors/5d5b096a83cd290019c71c12?event_id=5da9d7e6005110868d180000&i=gh&m=ci)

*Created by Calum Towers via Bugsnag*

**Comment by vatsim-uk-pa** [comment]
This issue has been linked to an error in Bugsnag
[**Illuminate\Database\QueryException** in **POST /mship/notification/acknowledge/4**](https://app.bugsnag.com/vatsim-uk/core/errors/5e1ada74d24cea00195ed23f?event_id=5e4065020055f132f4cf0000&i=gh&m=li)

**Comment by AxonC** [comment]
@atoff did you ever look into this?

**Comment by atoff** [comment]
@AxonC I did a while ago, but was never able to reproduce. Like there is even a test for it any everything. The only thing I can think that would cause it is a race condition, but honestly I have no idea anymore.
