### ISSUE TITLE
Partners Page

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#1578]
A page needs to be created to display the partners that we have. Ideally, these should be split into;

- Corporate Partners (i.e. commercial entities)
- Community Partners (other NFP organisations)

We will;

- Display their logo
- Display a short message about what they do
- Display their company / organisation name
- Track anyone that clicks a link to their site within our database

**Comment by aaronholtomcook** [comment]
1. Do we have a list of current partners?
2. Would this be fed from a CMS?
3. Have you thought about using GA instead of manual tracking?

**Comment by CalumTowers** [comment]
> * Do we have a list of current partners?
> * Would this be fed from a CMS?
> * Have you thought about using GA instead of manual tracking?

* Nope we don't have a partners page at present
* It'll be hard coded (in line with the other static content on the site)
* We use GA but we'll need to hit some endpoint within our own system before redirecting them to the external website otherwise it'll be quite hard to track within GA

**Comment by PlumbBum** [comment]
I've got the ball rolling with this page. It would obviously be nice to have some partners for when this feature is pushed to the live site. Is it worth anybody from Marketing reaching out to external sources expressing our interest in a partnership? Otherwise this feature is useless in its current state.

**Comment by CalumTowers** [comment]
> I've got the ball rolling with this page. It would obviously be nice to have some partners for when this feature is pushed to the live site. Is it worth anybody from Marketing reaching out to external sources expressing our interest in a partnership? Otherwise this feature is useless in its current state.

I've got a list. Ping me.
