### ISSUE TITLE
Handle CERT Downtime

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#1702]
## Error in Core

**ErrorException** in **App\Jobs\UpdateMember**
file_get_contents(https://cert.vatsim.net/vatsimnet/idstatusint.php?cid=1478028): failed to open stream: Connection timed out

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/core/errors/5d9e7cf863991e0019579a70?event_id=5e4b03510055e64537d50000&i=gh&m=ci)

## Stacktrace

    Jobs/UpdateMember.php:38 - App\Jobs\UpdateMember::handle
    Models/Mship/Account.php:258 - App\Models\Mship\Account::findOrRetrieve
    Console/Commands/NetworkData/ProcessNetworkData.php:165 - App\Console\Commands\NetworkData\ProcessNetworkData::processPilots
    Console/Commands/NetworkData/ProcessNetworkData.php:62 - App\Console\Commands\NetworkData\ProcessNetworkData::handle

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/core/errors/5d9e7cf863991e0019579a70?event_id=5e4b03510055e64537d50000&i=gh&m=ci)

*Created by VATSIM UK Admin via Bugsnag*

**Comment by CalumTowers** [comment]
`failed to open stream: Connection timed out`, `SSL: Handshake timed out` and `SSL: Connection reset by peer`

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Exception** in **App\Jobs\UpdateMember**](https://app.bugsnag.com/vatsim-uk/core/errors/5d9e7cf863991e0019579a70?event_id=5e5df8f700575e26d7640000&i=gh&m=fx)

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ErrorException** in **App\Jobs\UpdateMember**](https://app.bugsnag.com/vatsim-uk/core/errors/5d9e7cf863991e0019579a70?event_id=5e6d4d2600580b713d9e0000&i=gh&m=ra)
