### ISSUE TITLE
New SSO

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#1708]
https://auth.vatsim.net/login

**Comment by CalumTowers** [comment]
I’ve setup an org and had it approved, will invite others that need access too

**Comment by vatsim-uk-pa** [comment]
This issue has been linked to an error in Bugsnag
[**ErrorException** in **POST /login**](https://app.bugsnag.com/vatsim-uk/core/errors/5e5d4cc41af46f0018085252?event_id=5e9c526b0059e8624cf40000&i=gh&m=li)

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ErrorException** in **POST /login**](https://app.bugsnag.com/vatsim-uk/core/errors/5e5d4cc41af46f0018085252?event_id=5eb6bcf0005b2cad9e230000&i=gh&m=fx)

**Comment by vatsim-uk-pa** [comment]
This issue has been linked to an error in Bugsnag
[**ErrorException** in **POST /login**](https://app.bugsnag.com/vatsim-uk/core/errors/5f196dcf2be4a60018f8ef2b?event_id=5f196de1005b6ee12e740000&i=gh&m=li)

**Comment by vatsim-uk-pa** [comment]
This issue has been linked to an error in Bugsnag
[**ErrorException** in **GET /login-vatsim**](https://app.bugsnag.com/vatsim-uk/core/errors/5ed271e0af6f410018ae8cf1?event_id=5f1dee62005b7b018db00000&i=gh&m=li)

**Comment by vatsim-uk-pa** [comment]
This issue has been linked to an error in Bugsnag
[**ErrorException** in **GET /api/user**](https://app.bugsnag.com/vatsim-uk/core/errors/5f210b5d35bb5e00186f3230?event_id=5f21120f005b6d2879630000&i=gh&m=li)

**Comment by vatsim-uk-pa** [comment]
This issue has been unlinked from an error in Bugsnag
[**ErrorException** in **GET /api/user**](https://app.bugsnag.com/vatsim-uk/core/errors/5f210b5d35bb5e00186f3230?event_id=5f21120f005b6d2879630000&i=gh&m=ul)
