### ISSUE TITLE
Deprecate AutoTools

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#1736]
https://api.vatsim.net/api/

**Comment by vatsim-uk-pa** [comment]
This issue has been linked to an error in Bugsnag
[**ErrorException** in **App\Jobs\UpdateMember**](https://app.bugsnag.com/vatsim-uk/core/errors/5e7871b47fafe1001787611f?event_id=5e9264980059aaf100de0000&i=gh&m=li)

**Comment by vatsim-uk-pa** [comment]
This issue has been linked to an error in Bugsnag
[**ErrorException** in **GET /login-vatsim**](https://app.bugsnag.com/vatsim-uk/core/errors/5e7c699090e86a0017b6cb09?event_id=5e930c320059b7d6e6960000&i=gh&m=li)

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ErrorException** in **App\Jobs\UpdateMember**](https://app.bugsnag.com/vatsim-uk/core/errors/5e7871b47fafe1001787611f?event_id=5e98a1710059dbf8e7ef0000&i=gh&m=eu)

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ErrorException** in **App\Jobs\UpdateMember**](https://app.bugsnag.com/vatsim-uk/core/errors/5e7871b47fafe1001787611f?event_id=5eb60ed5005b395e4ea30000&i=gh&m=fx)
