### ISSUE TITLE
Automated Training Place Reminders

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#1785]
Once a day, we should check all users with an active training place and ;

- Ensure they have at least one session request in for each TG that they are training within
- Ensure they have availability in beyond today’s date

We should then log;

- The user that the check was completed against
- Which check ran
- Which RTS the check ran for
- The date and time the check ran
- The outcome of the check

When a check fails, we should trigger an email in three stages;

- Stage one warning
- Stage two warning
- TGI notification via Helpdesk

Notifications should only be sent once per stage.

One potential approach to achieve this will be by archiving checks to another table once a successful check for that has been met.

**Comment by AxonC** [comment]
Few notes on an initial investigation:
- If CID is > 999999, need to reference it as a CID without the first '1' e.g. 437521 = 1437521
- `session_done` represents the session having been completed which should represent the reference point for the availability warning
- the query should disregard anything which is not null in the `cancelled_datetime` column as this shouldn't count for the availability checker, as well a no show
