### ISSUE TITLE
Handle CERT 404

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#1799]
If CERT returns 404, handle appropriately.
At present, appears to be locking the database.

**Comment by vatsim-uk-pa** [comment]
This issue has been linked to an error in Bugsnag
[**ErrorException** in **App\Jobs\UpdateMember**](https://app.bugsnag.com/vatsim-uk/core/errors/5ec07cf480ab8b0017ee775d?event_id=5f066dc3005b7ddc14920000&i=gh&m=li)

**Comment by vatsim-uk-pa** [comment]
This issue has been linked to an error in Bugsnag
[**ErrorException** in **GET /login-vatsim**](https://app.bugsnag.com/vatsim-uk/core/errors/5eca87e79e4fb60019ff917f?event_id=5eded5cf005b7ad6e7d10000&i=gh&m=li)

**Comment by vatsim-uk-pa** [comment]
This issue has been linked to an error in Bugsnag
[**ErrorException** in **App\Jobs\UpdateMember**](https://app.bugsnag.com/vatsim-uk/core/errors/5ededcd45636c300173c2bc5?event_id=5ededcd6005b702662e70000&i=gh&m=li)
