### ISSUE TITLE
Update sector diagrams and sector page

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/core#1815]
New London sector images. Also redesign to make it more user friendly

![areasectors1](https://user-images.githubusercontent.com/12017284/85228324-c5bd9580-b3da-11ea-92d8-9c3b0a3c4399.png)
![egttsectors-ltc](https://user-images.githubusercontent.com/12017284/85725610-2dcaef00-b6ed-11ea-8bec-b7ace8af3761.png)

**Comment by CalumTowers** [comment]
@hsugden Are these changed images? Or do new images need making? Could do with some additional detail on how it can be improved and/or what exactly needs changing.

**Comment by cpawley** [comment]
These are the new images, the top would replace https://www.vatsim.uk/images/areasector1.png and the below would be a new image

**Comment by hsugden** [comment]
Oh I meant redesign the page to make it more user friendly - See PR, I’ve added in the collapsible blocks of text

New images are already made - they’re the ones in the original issue

**Comment by hsugden** [comment]
That said, I might work on the LTC image a bit and add some useful fixes etc.

**Comment by hsugden** [comment]
LTC image now updated, and PR ready
