### ISSUE TITLE
Text errors

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/core#1817]
I'm going to collect any errors with the text I can find in this issue and bung them all together:

- [Pilot Training page](https://www.vatsim.uk/pilots), first sentence doesn't need "the"
- [ATC Training page](https://www.vatsim.uk/atc)
-> Outdated information referring to TGMs - now Member Services who deal with training places
-> Outdated information referring to TG1 and TG2
- [Becoming A Mentor (ATC) page](https://www.vatsim.uk/atc/becoming-a-mentor) - again, references to old TGs and some of the headings can be moved down a level, I believe

**Comment by LevineRoss** [comment]
Hi Harry,

I'll edit these & send a request to have it pushed. 

- **In Progress**

**Comment by hsugden** [comment]
Oh no I'm geting to it thanks! I can't assign myself issues though

**Comment by LevineRoss** [comment]
Ahh,

Not a problem! 

Ross
