### ISSUE TITLE
API User Exception For Inactive Users

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#1865]
## Error in Core

**ErrorException** in **GET /api/user**
Trying to get property 'vatsim' of non-object

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/core/errors/5f210b5d35bb5e00186f3230?event_id=5f21120f005b6d2879630000&i=gh&m=ci)

## Stacktrace

    app/Http/Controllers/Api/OAuthUserController.php:33 - Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
    app/Http/Controllers/Api/OAuthUserController.php:33 - App\Http\Controllers\Api\OAuthUserController::view
    app/Http/Middleware/ApiTracking.php:26 - App\Http\Middleware\ApiTracking::handle

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/core/errors/5f210b5d35bb5e00186f3230?event_id=5f21120f005b6d2879630000&i=gh&m=ci)

*Created by Calum Towers via Bugsnag*

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ErrorException** in **GET /api/user**](https://app.bugsnag.com/vatsim-uk/core/errors/5f210b5d35bb5e00186f3230?event_id=5f2e87e0005b6ba1c46f0000&i=gh&m=ra)

**Comment by CalumTowers** [comment]
Fixed in #1881
