### ISSUE TITLE
Discord Invite Email

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#1875]
We should send an email to members that are;

- newly created
- home members of the division
- that we have an email address for

Inviting them to join our Discord server.

**Comment by atoff** [comment]
Do we want this to just be a new section in the welcome email?

Or do we want this so that we are inviting all current division members to notify them of the release of the discord server? (basically, is that list a list of ANDs or ORs)

**Comment by CalumTowers** [comment]
> Do we want this to just be a new section in the welcome email?
> 
> Or do we want this so that we are inviting all current division members to notify them of the release of the discord server? (basically, is that list a list of ANDs or ORs)

We can add it to the existing welcome email as that should only be going to home members anyway!
