### ISSUE TITLE
Allow one Teamspeak Connection Per CID

### ISSUE THREAD

**Issue by cpawley** [VATSIM-UK/core#1884]
Members with multiple Teamspeak Registrations (e.g. on multiple PCs) are eligable to connect these simultaneously. Any one individual should have no reason to use teamspeak more than once, maybe allow a small overlap (e.g. 10 minutes) before warning and kicking the member

**Comment by CalumTowers** [comment]
A lot of these that I have seen appear to be people using the same identity syncing over myTeamSpeak.

We can't have someone with the same identity connected twice.

We will also run into difficulties with nicknames too as we force people to use their VATSIM registered name but they cannot have that on the server twice either.

**Comment by CalumTowers** [comment]
Does this generally cause an issue?

If they're idle on one connection the server will boot them off after a while. 

Allowing multiple connections stops problems when one connection has timed out and hasn't yet disconnected.

**Comment by cpawley** [comment]
Mostly concerned about it being used by another member to access our systems without using their own credentials (we had a case of this a couple of weeks ago) - so less of the same member logging in twice but more using their account to facilitate someone else to join our systems.
