### ISSUE TITLE
Create a Glossary page

### ISSUE THREAD

**Issue by kye-taylor** [VATSIM-UK/core#1892]
As proclaimed in discord, not all members may know the definitions of some common acronyms used across the network. 

As mentions some that could be inclued are;

- OBS
- TWR
- ENR
- APP
- DEP
- ARR
- CTR
- S1
- S2
- S3
- C1
- C3
- I1
- I3
- P0-9
- VATUK
- VATSIM
- VATSIM UK
- Division
- Region
- ARTCC
- OTS
- CPT
- TG
- TGNC
- TGE
- TGAPP
- TGTWR

A way we could post this would be in 2 tables alongside each other
| Acronyms  | Meanings |
| ------------- | ------------- |  
| OBS  | Observer
| TWR  | Tower|
|ect|ect|

**Comment by CalumTowers** [comment]
Would be great to see a PR for this if someone would like to add a page to cover it!
