### ISSUE TITLE
TS Livestreaming in nickname

### ISSUE THREAD

**Issue by kye-taylor** [VATSIM-UK/core#1894]
Users with access to liverstreaming should have the ability to connect to the teamspeak as:

[Registared Name] - Streaming

or if at all possible 

[Registard Name] - [Online Possition] - Streaning

The later would be better for coordinations ect, but im unsure if possible

**Comment by chrisboyle** [comment]
I'm guessing those permissions are for streaming to official VUK channels? I stream to my own channel sometimes and would find this useful. Without it, currently I stay off TS when streaming (coordinating by text or VCCS), to avoid general chatter on the stream and specifically chatter that people didn't realise would be broadcast.

**Comment by kye-taylor** [comment]
Correct, VUK approved streamers have elevated privileges in core iirc to gain access to a discord channel.

**Comment by CalumTowers** [comment]
We're going to work with streamers to establish whether this would be useful, or whether a dedicated channel (for example) would be better.
