### ISSUE TITLE
Remove Unused Tables

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#1902]
There are a number of tables that are no longer used and we should drop. Associated models can also be removed.

- basic_users (was only used for Sendgrid & Mailgun, check if required elsewhere)
- community_group
- community_membership
- email_events
- jobs_pending (now using Redis)
- messages_thread
- messages_thread_participant
- messages_thread_post
- short_url (functionality was moved to vats.im)
- staff_account_position
- staff_attribute_position
- staff_attributes
- staff_positions
- staff_services
- stations (? check for uses)
- statistic (also remove from scheduler)
- sys_config (only had one use and is no longer needed)
- sys_timeline_action
- sys_timeline_entry

**Comment by atoff** [comment]
@CalumTowers Are we no longer using the Sendgrid / mailgun webhook things anymore then? The webhooks and stuff are still there but if we don't use it I will axe them

**Comment by CalumTowers** [comment]
> @CalumTowers Are we no longer using the Sendgrid / mailgun webhook things anymore then? The webhooks and stuff are still there but if we don't use it I will axe them
> 
> Also probably worth leaving in jobs_pending for local environments that might still use database

Only just caught this!

We don’t use the web hooks at the moment but I’d like to. We just need to work out what we are using long term in prod (considering SES). Once we do, I’ll throw an issue in here for us to add a properly tested endpoint back in.

Agree we can keep jobs_pending.
