### ISSUE TITLE
Admin Function - Statistics (Old 124)

### ISSUE THREAD

**Issue by NFarrington** [VATSIM-UK/core#211]
In gitlab by @A-Lawrence on Aug 31, 2015, 01:09

Admins should be allowed to generate statistics.

Keep it versatile and allow them to generate statistics on ANYTHING THEY WANT.

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Jan 11, 2016, 01:05

Removed ~98476 label

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Jan 11, 2016, 01:07

Removed ~98470 label

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Jun 19, 2016, 17:33

Removed ~98471 ~98472 ~137454 labels

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Aug 20, 2016, 11:49

Dashboard currently exists, showing an overview.  Custom statistics not yet available.

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Aug 20, 2016, 19:35

Removed ~98471 ~557445 labels

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Aug 21, 2016, 16:35

Milestone removed

**Comment by A-Lawrence** [comment]
This has been implemented.
