### ISSUE TITLE
Redirect Loop - Notifications (Old 332)

### ISSUE THREAD

**Issue by NFarrington** [VATSIM-UK/core#23]
In gitlab by @A-Lawrence on Aug 31, 2015, 01:07

In very specific circumstances, users encounter a redirect loop when they have to accept a notification before using services.

So far it's been members with secondary passwords, or with broken cookies...

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Aug 31, 2015, 01:10

mentioned in issue #297

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Aug 31, 2015, 01:18

mentioned in issue #292

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Aug 31, 2015, 01:18

mentioned in issue #293

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Aug 31, 2015, 01:18

mentioned in issue #294

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Aug 31, 2015, 01:18

mentioned in issue #295

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Aug 31, 2015, 01:18

mentioned in issue #296

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Aug 31, 2015, 01:18

mentioned in issue #297

**Comment by A-Lawrence** [comment]
Never really got to the bottom of this but no further incidents have been reported.
