### ISSUE TITLE
Member C(R)UD Events

### ISSUE THREAD

**Issue by NFarrington** [VATSIM-UK/core#330]
In gitlab by @A-Lawrence on Jan 4, 2016, 16:49

Properly add the C(R)UD events in the form of a trait, to any model we want to know about the CUD actions of.

There are currently create, update and delete methods defined in the boot of aModel, although these are of no use now.

Links to #315

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Jan 11, 2016, 00:51

mentioned in issue #331

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Feb 6, 2016, 13:19

Milestone removed

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Aug 20, 2016, 19:39

Removed ~98471 label

**Comment by A-Lawrence** [comment]
This is being considered as we continue to develop code.
