### ISSUE TITLE
Impersonation of banned member causes issue

### ISSUE THREAD

**Issue by NFarrington** [VATSIM-UK/core#348]
In gitlab by @A-Lawrence on Jan 11, 2016, 23:52

TOO MANY REDIRECTS.  Fix plz.

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Feb 8, 2016, 19:33

mentioned in issue #381

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Jun 19, 2016, 21:04

Assignee removed

**Comment by A-Lawrence** [comment]
No further issues.
