### ISSUE TITLE
Remove auth.user middleware

### ISSUE THREAD

**Issue by NFarrington** [VATSIM-UK/core#352]
In gitlab by @NFarrington on Jan 12, 2016, 14:45

The auth.user middleware will be removed, in favour of acknowledging the user elsewhere.

When SSO returns the payload, the CID will be stored in the session (and the user updated as normal), but the user will not be logged in via Auth::login() (since they're not get authenticated).

When doing resets (anything with the auth.user middleware) their CID will be displayed from the session, and they will have the option to "logout" if necessary.

Only when the user is fully authenticated will Auth::login() be called.

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Feb 8, 2016, 19:33

mentioned in issue #381

**Comment by A-Lawrence** [comment]
@NFarrington dealt with this when modifying the middleware for authentication.
