### ISSUE TITLE
Tidy up routes.php - named route groups

### ISSUE THREAD

**Issue by NFarrington** [VATSIM-UK/core#368]
In gitlab by @A-Lawrence on Feb 6, 2016, 14:55

Look at whether this would help to tidy up routes.php slightly.

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Feb 6, 2016, 15:37

mentioned in commit 8ade4d37823dd12deea8978001c6a0b2591e995b

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Feb 7, 2016, 20:13

Milestone removed

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Aug 20, 2016, 19:39

Removed ~98471 label

**Comment by A-Lawrence** [comment]
N/A.
