### ISSUE TITLE
Core Admin Responsive

### ISSUE THREAD

**Issue by NFarrington** [VATSIM-UK/core#420]
In gitlab by @CalumTowers on Jul 31, 2016, 16:42

When viewing core adm on a mobile device, or a screen with limited width, there is no search bar. This renders it useless.

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Aug 1, 2016, 16:20

Milestone removed

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Aug 24, 2016, 00:10

Milestone removed

**Comment by CalumTowers** [comment]
Is there any chance we can look into this? Just need to menu bar to appear somewhere on Core ADM on mobiles
