### ISSUE TITLE
Auto-create applications for S1+

### ISSUE THREAD

**Issue by NFarrington** [VATSIM-UK/core#453]
In gitlab by @A-Lawrence on Aug 20, 2016, 19:33

Where a member _appears_ in our divisional feed and is S1+ rated, create a transfer application for them automatically.

They should then be contacted and asked to complete the remainder of them.

This may require the creation of a NewDivisionMember event.

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Aug 20, 2016, 19:35

Removed ~98471 label

**Comment by NFarrington** [comment]
@CalumTowers This is going to be implemented as a notification that they need to start their application (since the first step is accepting the terms, there's not much point actually creating one).

Could you please liase with Barrie on what he would like the email content to be? Otherwise I'll happily cobble something together.

**Comment by A-Lawrence** [comment]
For context, it's worth noting that the discussion surrounding this was that if they've gone out of their way to use the .net deployment tool (which ignores all restrictions), then they should be deemed to have "agreed" to starting their application and as such, enter the queue.  Failure to complete should then result in them being removed.

^ Not sure if that helps clarify what my cryptic comments meant.

**Comment by CalumTowers** [comment]
This is on hold pending a review of CERT 2.0.
