### ISSUE TITLE
Remove legacy URL redirect in VT/routes.php

### ISSUE THREAD

**Issue by NFarrington** [VATSIM-UK/core#539]
In gitlab by @A-Lawrence on Sep 2, 2016, 13:40

I've added:

```
Route::get("/view/{applicationByPublicId}", function(\App\Modules\Visittransfer\Models\Application $application){
            return Redirect::route("visiting.application.view", [$application->public_id]);
        });
```

To support those applications in progress presently.  We'll remove this towards the end of September.

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Dec 2, 2016, 21:47

changed milestone to %27

**Comment by A-Lawrence** [comment]
This already seems to have been resolved.
