### ISSUE TITLE
Remove the legacy checks in addState()

### ISSUE THREAD

**Issue by NFarrington** [VATSIM-UK/core#543]
In gitlab by @A-Lawrence on Sep 2, 2016, 15:57

Currently addState checks for null values as a legacy thing.  I've queued up 16,000 jobs over the next 3 weeks to ensure there won't be any NULL entries.

Review this at the end of September with a view to removing those legacy checks.

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Dec 2, 2016, 21:47

changed milestone to %27

**Comment by A-Lawrence** [comment]
There were 46 remaining entries in the live database.  These remained as they are inactive, suspended and without division/region.  They've moved to state 6 (UNKNOWN).

```
UPDATE mship_account_state SET state_id = 6 WHERE state_id NOT IN (1,2) AND division IS NULL AND region IS NULL AND end_at IS NULL;
```

Fix has been submitted as PR.
