### ISSUE TITLE
VT Missing/Incorrect Permissions

### ISSUE THREAD

**Issue by NFarrington** [VATSIM-UK/core#547]
In gitlab by @A-Lawrence on Sep 2, 2016, 18:44

Resolve permission issues:

* adm/visit-transfer/facility/create (missing facility)
* adm/visit-transfer/facility/*/update (missing entirely)
* adm/visit-transfer/application/*/check/met (missing entirely)

These need to be retrospectively added to an old migration somewhere. Or a new one... as long as they're migrated.

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Dec 2, 2016, 21:47

changed milestone to %27

**Comment by A-Lawrence** [comment]
This has been added to a new migration for future users.
