### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalErrorException in GET /adm

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#577]
## Error in VATSIM-UK/Core

**Symfony\Component\Debug\Exception\FatalErrorException** in **GET /adm**
Class 'App\Http\Controllers\Adm\Bugsnag' not found

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/5842ccb71e51a96a2ae81cad?event_id=5842ce962ff6911200758359)

## Stacktrace

    \app\Http\Controllers\Adm\Authentication.php:19 - Symfony\Component\Debug\Exception\FatalErrorException::__construct
    \app\Http\Controllers\Adm\AdmController.php:54 - App\Http\Controllers\Adm\AdmController::App\Http\Controllers\Adm\{closure}
    \app\Http\Middleware\TrackInactivity.php:41 - App\Http\Middleware\TrackInactivity::handle

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/5842ccb71e51a96a2ae81cad?event_id=5842ce962ff6911200758359)

**Comment by A-Lawrence** [comment]
Was a test error from development.  Can be closed safely.

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Symfony\Component\Debug\Exception\FatalErrorException** in **GET /adm**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/5842ccb71e51a96a2ae81cad?event_id=5842cec739a4401100874cd9)
