### ISSUE TITLE
ErrorException in App\Jobs\Mship\Account\MemberCertUpdate

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#589]
## Error in VATSIM-UK/Core

**ErrorException** in **App\Jobs\Mship\Account\MemberCertUpdate**
file_get_contents(): Peer certificate CN=`vatsim-uk.co.uk' did not match expected CN=`cert.vatsim.net'

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/5844481e1e51a96a2ae82994?event_id=5844481eaad094120039aec7)

## Stacktrace

    app/Jobs/Mship/Account/MemberCertUpdate.php:41 - Vatsim\Xml\Facades\XML::getData
    app/Jobs/Mship/Account/MemberCertUpdate.php:41 - App\Jobs\Mship\Account\MemberCertUpdate::handle

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/5844481e1e51a96a2ae82994?event_id=5844481eaad094120039aec7)

**Comment by A-Lawrence** [comment]
Fixed upstream in the A-Lawrence/VatsimXML repo.

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ErrorException** in **App\Jobs\Mship\Account\MemberCertUpdate**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/5844481e1e51a96a2ae82994?event_id=586c61d077cd921000e62ae3)

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ErrorException** in **App\Jobs\Mship\Account\MemberCertUpdate**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/5844481e1e51a96a2ae82994?event_id=587cf89a7f58881100ef6978)

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ErrorException** in **App\Jobs\Mship\Account\MemberCertUpdate**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/5844481e1e51a96a2ae82994?event_id=58829aa02ada3b1100418c41)

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ErrorException** in **App\Jobs\Mship\Account\MemberCertUpdate**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/5844481e1e51a96a2ae82994?event_id=58bb2775eda5dd1100caaad2)

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**ErrorException** in **App\Jobs\Mship\Account\MemberCertUpdate**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/5844481e1e51a96a2ae82994?event_id=591a67d3e3ae0a001af3b1eb&i=gh&m=ra)

**Comment by atoff** [comment]
This should be fixed by the patch applied in VatsimXML/4f5f62d

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ErrorException** in **App\Jobs\Mship\Account\MemberCertUpdate**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/5844481e1e51a96a2ae82994?event_id=591a67d3e3ae0a001af3b1eb&i=gh&m=fx)
