### ISSUE TITLE
How should ATC Sessions crossing midnight be handled?

### ISSUE THREAD

**Issue by A-Lawrence** [VATSIM-UK/core#599]
There is a requirement to provide statistics for the following time periods:
* 24 hour
* Weekly
* Monthly
* Yearly

Furthermore, with the introduction of Community leaderboards, points will be awarded for full blocks of 90 minutes of controlling completed.

These introduce some an interesting question of how we correctly calculate the following values:
* How many ATC Sessions were conducted in the given time period (24H, 7D, 1M, 1Y)
* How many hours of ATC were provided in that period.

The second is easy, we can calculate the number of minutes.  The first, however, introduces a range of issues:
* Can sessions count on two days, when they span midnight?
* How do we handle the "controlling period" to claim community points, when it spans midnight?
* What about if the start/end straddles 2 months (which would be 2 different competition periods)?

There are several options here:

## Option 1 ##
End ATC sessions at midnight and create a new one.
Raises the question, when community points are awarded for 90 minute sessions, this might ruin that.

## Option 2 ##
Allow them to progress beyond midnight.
Raises the question _How do we correctly calculate the total number of complete ATC sessions in a time period_? Are they double counted?

**Comment by bjoplin** [comment]
Can it be measured per session if

23:00 (D1) - 00:30 (D2)

is awarded to day 1 and

23:30-01:00

is awarded to day 2?

i.e the heavier weighting lands on the relavnt day's awards so the session only gets credited once to the day that spent most time?

**Comment by NFarrington** [comment]
@bjoplin: And I assume if a session was from 22:30-01:30, that would then be credited to both days, since there is a total of >=90 minutes controlled on each day?

**Comment by bjoplin** [comment]
@NFarrington yep sounds reasonable - really we could do anything we needed to so long as it's made clear to the membership how the system is counting.

**Comment by lpetersctc** [comment]
I think Barrie's suggestion makes the most sense. To keep it simple we could just say any qualifying session that starts before 2300z counts as Day 1 and anything from 2300z onwards counts as Day 2.
