### ISSUE TITLE
As a member, I should be able to see other member's public feedback

### ISSUE THREAD

**Issue by A-Lawrence** [VATSIM-UK/core#607]
_Pending review of consultation feedback._

When viewing another member's profile, any feedback that is public should be visible.

There should be an option of disabling public feedback _entirely_.  It should not be possible to _select_ feedback to display.

**Comment by atoff** [comment]
We have decided not to implement public feedback due the the possibility of it being abused. If this is requested by members or DSG later on, we can look at an appropriate implementation
