### ISSUE TITLE
Soft Delete Qualifications

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#609]
Soft deleting qualifications does not appear to function. When a value != NULL is given, the qual still appears in both Core ADM and on the Dashboard for the end user.

Expected outcome: qual is hidden.

It would be useful for Core ADM to show the rating as deleted, when it was deleted and provide the facility to remove a rating manually without the need to go into PMA.

**Comment by NFarrington** [comment]
Qualifications will now be soft deleted - up until this point, qualifications will have been hard deleted if they are no longer present.

Removing a rating manually is not possible - this is done automatically from information pulled from Cert, and therefore a deleted rating would be re-added soon after. Ratings that the member no longer holds will be automatically removed.
