### ISSUE TITLE
ErrorException in POST /application/5V97R69Y/referees

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#617]
## Error in VATSIM-UK/Core

**ErrorException** in **POST /application/5V97R69Y/referees**
Trying to get property of non-object

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/5849c4e51e51a96a2ae87535?event_id=5849c4e558e20d11007c56a8)

## Stacktrace

    app/Modules/Visittransfer/Http/Requests/ApplicationRefereeAddRequest.php:71 - Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
    app/Modules/Visittransfer/Http/Requests/ApplicationRefereeAddRequest.php:71 - App\Modules\Visittransfer\Http\Requests\ApplicationRefereeAddRequest::getValidatorInstance
    app/Http/Controllers/BaseController.php:50 - App\Http\Controllers\BaseController::App\Http\Controllers\{closure}
    app/Http/Middleware/UserMustReadNotifications.php:33 - App\Http\Middleware\UserMustReadNotifications::handle
    app/Http/Middleware/AuthUserFull.php:33 - App\Http\Middleware\AuthUserFull::handle
    app/Http/Middleware/TrackInactivity.php:41 - App\Http\Middleware\TrackInactivity::handle

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/5849c4e51e51a96a2ae87535?event_id=5849c4e558e20d11007c56a8)

**Comment by A-Lawrence** [comment]
Issue identified - we didn't have the full details of applicant & referee. The validation is quite officious and refuses to budge until we do - this has then triggered a timeout of applications.  Improved this part of the validation so it doesn't reject an application if we're missing data.

**Comment by A-Lawrence** [comment]
v2.4
