### ISSUE TITLE
How should circuits be counted for airfield statistics?

### ISSUE THREAD

**Issue by A-Lawrence** [VATSIM-UK/core#619]
There are 4 possible methods of displaying statistics, in relation to circuits:

Circuits can be counted as:
* Departures
* Arrivals
* Both/Total Movements
* Neither

**Comment by AndyTWF** [comment]
Assuming that this data isn't real-time and therefore we can't detect if an aircraft has done a touch and go, I'd say something like:

- If aircraft has dest as some other airfield: count as departure
- If dest and dep are the same, count 1 in each (assume that they'll come back to where they started).

**Comment by AndyTWF** [comment]
Sorry... I pushed the wrong damn button.
