### ISSUE TITLE
InvalidArgumentException in GET /mship/manage/teamspeak/new

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#651]
## Error in VATSIM-UK/Core

**InvalidArgumentException** in **GET /mship/manage/teamspeak/new**
Unexpected data found.

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/584edad31e51a96a2ae8a979?event_id=584edad30d6ce0110038e6a3)

## Stacktrace

    app/Models/Model.php:92 - App\Models\Model::toArray
    app/Models/Model.php:92 - App\Models\Model::toArray
    app/Models/Model.php:92 - App\Models\Model::toArray
    app/Models/Mship/Account.php:1365 - App\Models\Mship\Account::toArray
    app/Http/Controllers/TeamSpeak/Registration.php:79 - Illuminate\Support\Facades\Log::info
    app/Http/Controllers/TeamSpeak/Registration.php:79 - App\Http\Controllers\TeamSpeak\Registration::createRegistration
    app/Http/Controllers/TeamSpeak/Registration.php:23 - App\Http\Controllers\TeamSpeak\Registration::getNew
    app/Http/Controllers/BaseController.php:50 - App\Http\Controllers\BaseController::App\Http\Controllers\{closure}
    app/Modules/Community/Http/Middleware/MustHaveCommunityGroup.php:29 - App\Modules\Community\Http\Middleware\MustHaveCommunityGroup::handle
    app/Http/Middleware/UserMustReadNotifications.php:33 - App\Http\Middleware\UserMustReadNotifications::handle
    app/Http/Middleware/AuthUserFull.php:33 - App\Http\Middleware\AuthUserFull::handle
    app/Http/Middleware/TrackInactivity.php:41 - App\Http\Middleware\TrackInactivity::handle

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/584edad31e51a96a2ae8a979?event_id=584edad30d6ce0110038e6a3)

**Comment by A-Lawrence** [comment]
Fixed on production and ported backwards by @NFarrington

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**InvalidArgumentException** in **GET /mship/manage/teamspeak/new**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/584edad31e51a96a2ae8a979?event_id=58713f1ee113741200d9185a)

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**InvalidArgumentException** in **GET /mship/manage/teamspeak/new**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/584edad31e51a96a2ae8a979?event_id=5871464849732f1000cde966)
