### ISSUE TITLE
GuzzleHttp\Exception\RequestException in app/Console/Commands/Command.php:195

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#654]
## Error in VATSIM-UK/Core

**GuzzleHttp\Exception\RequestException** in **app/Console/Commands/Command.php:195**
cURL error 51: Unable to communicate securely with peer: requested domain name does not match the server's certificate. (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/584fd1311e51a96a2ae8b6e0?event_id=584fd1310100a01100bc84b4)

## Stacktrace

    app/Console/Commands/Command.php:195 - App\Console\Commands\Command::sendSlackSuccess
    app/Console/Commands/MembersCertUpdate.php:46 - App\Console\Commands\MembersCertUpdate::handle

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/584fd1311e51a96a2ae8b6e0?event_id=584fd1310100a01100bc84b4)

**Comment by A-Lawrence** [comment]
This has been resolved upstream in A-Lawrence/VatsimXML.

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**GuzzleHttp\Exception\RequestException** in **app/Console/Commands/Command.php:195**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/584fd1311e51a96a2ae8b6e0?event_id=586fd067befc7913006ffb87)
