### ISSUE TITLE
Overlapping Texts

### ISSUE THREAD

**Issue by AndyTWF** [VATSIM-UK/core#655]
On the user dashboard, the text in all boxes with column layouts has a tendency to overflow into neighboring columns when using a small screen - still intelligible but not particularly pretty.

Noticed in Chrome on a 15" laptop.

**Comment by A-Lawrence** [comment]
13" laptop.

![image](https://cloud.githubusercontent.com/assets/1240362/21204400/1ccd57e2-c24f-11e6-92d1-9ff7359f886a.png)

**Comment by A-Lawrence** [comment]
Any chance you can take a look at this, please @atoff?
