### ISSUE TITLE
Symfony\Component\Console\Exception\CommandNotFoundException in vendor/symfony/console/Application.php:536

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#656]
## Error in VATSIM-UK/Core

**Symfony\Component\Console\Exception\CommandNotFoundException** in **vendor/symfony/console/Application.php:536**
Command "statistic" is not defined.

Did you mean one of these?
    sys:statistics:daily
    visittransfer:statistics:daily

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/5850616e1e51a96a2ae8c00d?event_id=5850616f4f47e413008f3bbb)

## Stacktrace

    vendor/symfony/console/Application.php:536 - Symfony\Component\Console\Application::find

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/5850616e1e51a96a2ae8c00d?event_id=5850616f4f47e413008f3bbb)

**Comment by A-Lawrence** [comment]
This was caused through my own stupidity of typing an artisan command wrong on production.  invalid.
