### ISSUE TITLE
Symfony\Component\Process\Exception\ProcessTimedOutException in /var/www/core/shared/vendor/symfony/process/Process.php:1226

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#723]
## Error in VATSIM-UK/Core

**Symfony\Component\Process\Exception\ProcessTimedOutException** in **/var/www/core/shared/vendor/symfony/process/Process.php:1226**
The process "'/usr/bin/php' 'artisan' queue:work '' --once --queue='emails,high,med,default,low' --delay=0 --memory=128 --sleep=3 --tries=3 --env='production'" exceeded the timeout of 60 seconds.

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/585bea3c1e51a96a2ae94456?event_id=585bea3ce2eb4711005198d7)

## Stacktrace

    /var/www/core/shared/vendor/symfony/process/Process.php:1226 - Symfony\Component\Process\Process::checkTimeout

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/585bea3c1e51a96a2ae94456?event_id=585bea3ce2eb4711005198d7)

**Comment by A-Lawrence** [comment]
Any chance you can have a look at this, please @NFarrington?

**Comment by NFarrington** [comment]
These all appear to have been caused by Slack outages (https://status.slack.com/2016-12/92ca538bc556e84f) or our web server upgrades.
