### ISSUE TITLE
GuzzleHttp\Exception\RequestException in Illuminate\Notifications\SendQueuedNotifications

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#724]
## Error in VATSIM-UK/Core

**GuzzleHttp\Exception\RequestException** in **Illuminate\Notifications\SendQueuedNotifications**
cURL error 51: Unable to communicate securely with peer: requested domain name does not match the server's certificate. (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/585bf8b41e51a96a2ae94552?event_id=585bf8b43b876f110008095b)

## Stacktrace

    /var/www/core/shared/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187 - GuzzleHttp\Handler\CurlFactory::createRejection

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/585bf8b41e51a96a2ae94552?event_id=585bf8b43b876f110008095b)

**Comment by A-Lawrence** [comment]
Any chance you can have a look at this, please @NFarrington?

**Comment by NFarrington** [comment]
Failed Slack notification, error occurred during https://status.slack.com/2016-12/92ca538bc556e84f

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**GuzzleHttp\Exception\RequestException** in **Illuminate\Notifications\SendQueuedNotifications**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/585bf8b41e51a96a2ae94552?event_id=58973e14ac4a74110044d346)

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**GuzzleHttp\Exception\RequestException** in **Illuminate\Notifications\SendQueuedNotifications**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/585bf8b41e51a96a2ae94552?event_id=589a437c11101d1100d298dc)
