### ISSUE TITLE
GuzzleHttp\Exception\ConnectException in Illuminate\Notifications\SendQueuedNotifications

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#726]
## Error in VATSIM-UK/Core

**GuzzleHttp\Exception\ConnectException** in **Illuminate\Notifications\SendQueuedNotifications**
cURL error 6: Could not resolve host: U2AA471PU; Name or service not known (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/585d34fe1e51a96a2ae95756?event_id=585d34fe59355d1100824498)

## Stacktrace

    /var/www/core/shared/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186 - GuzzleHttp\Handler\CurlFactory::createRejection

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/585d34fe1e51a96a2ae95756?event_id=585d34fe59355d1100824498)

**Comment by A-Lawrence** [comment]
Any chance you can have a look at this, please @NFarrington?

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**GuzzleHttp\Exception\ConnectException** in **Illuminate\Notifications\SendQueuedNotifications**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/585d34fe1e51a96a2ae95756?event_id=587cd1fc0a960d1000421b6d)

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**GuzzleHttp\Exception\ConnectException** in **Illuminate\Notifications\SendQueuedNotifications**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/585d34fe1e51a96a2ae95756?event_id=58849ed4e4d9c911009f0b6e)

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**GuzzleHttp\Exception\ConnectException** in **Illuminate\Notifications\SendQueuedNotifications**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/585d34fe1e51a96a2ae95756?event_id=589a357615e7431200bca510)
