### ISSUE TITLE
window.onerror in /mship/manage/teamspeak/new

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#729]
## Error in VATSIM-UK/Core

**window.onerror** in **/mship/manage/teamspeak/new**
Uncaught Error: Socket server did not execute the callback for setAttributes with data : {"name":"Jack Endersby (1327159)","email":"jojack444.j@gmail.com"}

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/585dc3091e51a96a2ae95f96?event_id=585dc3092317e9110090a8b9)

## Stacktrace

    https://embed.tawk.to/57bb3bfca767d83b45e79605/1aqq3gev7:209 - e.onerror

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/585dc3091e51a96a2ae95f96?event_id=585dc3092317e9110090a8b9)

**Comment by A-Lawrence** [comment]
Any chance you can have a look at this, please @NFarrington?
