### ISSUE TITLE
Pilot Rating Tooltip Invalid

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#736]
Should show date rating was achieved.

![88a013d5d36c4a2f813a3eaa54839da5](https://cloud.githubusercontent.com/assets/7726792/21509271/4b9ac7dc-cc7f-11e6-9fd4-bac503d98e90.png)

**Comment by A-Lawrence** [comment]
Can you give me the ID of the row from mship_account_qualification please?
