### ISSUE TITLE
window.onerror in /mship/security/auth

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#742]
## Error in VATSIM-UK/Core

**window.onerror** in **/mship/security/auth**
TypeError: undefined is not an object (evaluating '__gCrWeb.autofill.extractForms')

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/5863b5e31e51a96a2ae9969a?event_id=5863b5e3e63d141100b42a81)

## Stacktrace

    https://embed.tawk.to/57bb3bfca767d83b45e79605/1aqq3gev7:209 - onerror

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core/errors/5863b5e31e51a96a2ae9969a?event_id=5863b5e3e63d141100b42a81)

**Comment by NFarrington** [comment]
Fixed by a06fa991dba32aadf9a97a31cc1bc01be7c039fa
