### ISSUE TITLE
TypeError in /adm/search

### ISSUE THREAD

**Issue by NFarrington** [VATSIM-UK/core#756]
## Error in VATSIM-UK/Core

**TypeError** in **/adm/search**
Uncaught TypeError: Cannot read property 'defaults' of undefined

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-1/errors/586901eb1e51a96a2ae9c839?event_id=586901eb78764c1100f82db5)

## Stacktrace

    https://core.vatsim-uk.co.uk/assets/js/plugins/datatables/dataTables.bootstrap.js:2 - 

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-1/errors/586901eb1e51a96a2ae9c839?event_id=586901eb78764c1100f82db5)

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **/adm/visit-transfer/application/open**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-js/errors/586901eb1e51a96a2ae9c839?event_id=5879690696e6e11100346846)

**Comment by A-Lawrence** [comment]
Any chance you can take a look at this, please @atoff?

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**TypeError** in **/adm/mship/role**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-js/errors/586901eb1e51a96a2ae9c839?event_id=589b90dda8538d1100086c18)
