### ISSUE TITLE
Push to wslogging based on verbosity settings

### ISSUE THREAD

**Issue by A-Lawrence** [VATSIM-UK/core#782]
Change the main Command class to only push messages to wslogging based on the level of verbosity specified for the task.

**Comment by A-Lawrence** [comment]
@atoff - potentially able to tackle this for me?

**Comment by atoff** [comment]
Sure 👍

**Comment by A-Lawrence** [comment]
Ideally full verbosity (-vvv) should report both success and errors.  We generally won't enable that for any/many of them though.

Single verbosity should output just errors.
