### ISSUE TITLE
AIS Charts

### ISSUE THREAD

**Issue by atoff** [VATSIM-UK/core#785]
Looking at the long run, it might be nice to incorporate charts/airfield information into an AIS module/main site airfield information pages.

API's such as http://www.aircharts.org/api and data such as openAIP would allow us to easily implement this.

**Comment by NFarrington** [comment]
At this time, I don't foresee this being implemented based on the value of what it would add. We currently have a link to the AIS charts, which should be enough.

This may be something we reconsider after the website and CTS merges, when we have more of an idea of where our airport info is sourced from, and how everything ties in with those pages.
