### ISSUE TITLE
TS Control via Core

### ISSUE THREAD

**Issue by A-Lawrence** [VATSIM-UK/core#787]
It would be beneficial to allow for the complete control of TS rooms via Core:

- Addition of new permanent rooms
- Modified of existing rooms
- Addition of password to existing rooms
- Creation of temporary (time limited?) rooms

This will mean that TeaMan always remains up to date.

Each room should have the following settings:

- _Boolean_: Included in idle time checks
- _Boolean_: Extended idle time permitted

This should, ideally, be a new module:
- Also incorporate TeaMan into the module
- Move the UI side into this module

**Comment by NFarrington** [comment]
Closed unimplemented
