### ISSUE TITLE
getPolicyFor method

### ISSUE THREAD

**Issue by A-Lawrence** [VATSIM-UK/core#804]
Previous, when calling the `Gate::getPolicyFor($class)` method, an exception was thrown if no policy could be found. Now, the method will return null if no policy is found for the given class. If we call this method directly, make sure we refactor our try / catch to a check for null:

```php
$policy = Gate::getPolicyFor($class);

if ($policy) {
    // code that was previously in the try block
} else {
    // code that was previously in the catch block
}
```

**Comment by NFarrington** [comment]
No references
