### ISSUE TITLE
Container - share method removed

### ISSUE THREAD

**Issue by A-Lawrence** [VATSIM-UK/core#811]
The share method has been removed from the container. This was a legacy method that has not been documented in several years. If we are using this method (might be worth just verifying modules), we need to consider an approach like pushing singleton PRs to those modules:

```php
$container->singleton('foo', function () {
    return 'foo';
});
```

**Comment by NFarrington** [comment]
The following package dependencies use this and require updating:

**alawrence/laravel-ipboard**

- Status: None
- Plan of action: Ask package maintainer to update (@A-Lawrence)

**maknz/slack**

- Status: PR submitted Feb 13 (https://github.com/maknz/slack/pull/83), no action taken
- Plan of action: Package no longer maintained, fork repo and update 

**vatsim/sso**

- Status: PR submitted Feb 22 (https://github.com/KHardern/VatsimSSO/pull/6), no action taken
- Plan of action: Ask package maintainer to update / fork repo and update until PR accepted

**vatsim/xml**

- Status: None
- Plan of action: Ask package maintainer to update (@A-Lawrence)
