### ISSUE TITLE
account_state->division

### ISSUE THREAD

**Issue by jamiefox** [VATSIM-UK/core#831]
On the CTS, when a new member logs in for the first time, the data from Core is checked to see if they are not a member of the UK division. The check is if (!$member->account_state->division), where $member is json_decode($response)->data (and $response is the HTTP response body returned by cURL).

There seems to be something wrong with this data, as it is not detecting UK members in most or possibly all cases. According to the logs this started on 2nd September 2016, if that means anything.

Fortunately there is fallback code that will allow a UK member to create an account even if the data from Core is incorrect, which is why new members haven't been locked out by this bug.

Has there been a change to the JSON data structure, or some other reason why $member->account_state->division would evaluate as false for a home UK member?

**Comment by jamiefox** [comment]
From logs I can see that the data we're getting is of this form (this is after JSON decoding in PHP):
 'account_state' =>
  array (
    0 =>
    stdClass::__set_state(array(
       'code' => 'DIVISION',
       'type' => 'perm',
       'name' => 'Division',
       'division' =>
      array (
        0 => 'GBR',
      )

So the account state and division are in a one-element array, which is surprising. (i.e. $member->account_state[0]->division[0] would work)

Are these supposed to be arrays, and what is the expected form for a member whose home division is not the UK division?

**Comment by A-Lawrence** [comment]
The appropriate returns you're after, can be found here: https://github.com/VATSIM-UK/core/blob/development/app/Http/Controllers/Sso/Security.php

You're better off using `account_state_current` which will return DIVISION, VISITOR, TRANSFERRING, INTERNATIONAL or REGIONAL.

**Comment by A-Lawrence** [comment]
In answer to your other question, it's meant to be an array as a member can hold different states (REGION & VISITOR).  I have, however, noticed that the to/from dates are missing from that data.

**Comment by jamiefox** [comment]
Thanks. Is there a definition of the meaning of DIVISION, VISITOR, TRANSFERRING, INTERNATIONAL or REGIONAL?

And to confirm, these are possible values of account_state_current, which is defined in the code as primary_state->name? From the upper case it looks to me like they might be values of 'code' rather than 'name', hence this question to check.

**Comment by NFarrington** [comment]
@jamiefox Does the following help?

- DIVISION: A member of the division (GBR)
- REGIONAL: A member of another division within the EUR VATSIM region
- INTERNATIONAL: Neither DIVISION nor REGIONAL (i.e. from another VATSIM region)
- VISITING: Members from other divisions who are currently visiting
- TRANSFERRING: Members from other divisions who are transferring to the UK

A member will only ever have one of the first 3 at any one time (and should always have one of these), and may also have the 4th and 5th at any time.

It looks like the data returned is the `name`, which at the moment is identical to the `code` except for the capitalisation.
