### ISSUE TITLE
Exception in POST /mship/manage/email/add

### ISSUE THREAD

**Issue by vatsim-uk-pa** [VATSIM-UK/core#833]
## Error in VATSIM-UK/Core (Laravel)

**Exception** in **POST /mship/manage/email/add**
Serialization of 'Closure' is not allowed

[View on Bugsnag](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/588387161e51a96a2aeb1516?event_id=58838716ec7d1a120022a599)

## Stacktrace

    bootstrap/cache/compiled.php:12321 - serialize

[View full stacktrace](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/588387161e51a96a2aeb1516?event_id=58838716ec7d1a120022a599)

**Comment by A-Lawrence** [comment]
Can you take a look at this please @atoff ?

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Exception** in **POST /mship/manage/email/add**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/588387161e51a96a2aeb1516?event_id=58838716ec7d1a120022a599)

**Comment by atoff** [comment]
Have a feeling that it was something to do with his previous secondary email being deleted from the db as per his ticket. It seems to still have functioned correctly, however.

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Exception** in **POST /mship/manage/email/add**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/588387161e51a96a2aeb1516?event_id=58d6c656cf6e8b1700c24ecd)

**Comment by vatsim-uk-pa** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Exception** in **POST /mship/manage/email/add**](https://app.bugsnag.com/vatsim-uk/vatsim-uk-slash-core-laravel/errors/588387161e51a96a2aeb1516?event_id=58d6c656cf6e8b1700c24ecd)
