### ISSUE TITLE
Utilise Form Request Validators (Old 344)

### ISSUE THREAD

**Issue by NFarrington** [VATSIM-UK/core#9]
In gitlab by @A-Lawrence on Aug 31, 2015, 01:07

To stop cluttering up our models and controllers with so much junk, let's use them.

For reference: http://laravel.com/docs/5.1/validation#form-request-validation

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Dec 20, 2015, 18:51

Removed ~98469 label

**Comment by NFarrington** [comment]
In gitlab by @A-Lawrence on Jan 11, 2016, 01:08

This has been started in commit 8700ae7195669d2604b631972f18d8120ae3b248

**Comment by NFarrington** [comment]
In gitlab by @NFarrington on Jan 14, 2016, 14:05

@A-Lawrence Can we decide which classes need this change at some point? Otherwise we can close this and simply bear it in mind for future.

**Comment by A-Lawrence** [comment]
Closing as this can be kept in mind during future development.  Specific classes can have the features added as a new issue.
