### ISSUE TITLE
Applications that require training never marked "completed"

### ISSUE THREAD

**Issue by atoff** [VATSIM-UK/core#918]
Applications for facilities that require training currently only get as far as the application being accepted. This means that they are unable to start a new application because an accepted application is still classed as an open application.

Applications that require training and are marked as "accepted" need to have the functionality to mark as "training completed", and therefore mark the application as complete.

**Comment by CalumTowers** [comment]
Perhaps this should be an automated check, especially for Pilot Rating as they do not need to be ratified.
I.E. once an account has a P2 qual added, they should be marked as completed.

I will discuss with Barrie the exact circumstances that people should and should not be allowed to create new applications.

**Comment by CalumTowers** [comment]
Will resolve manually for now with #1081 with a view to automate in future
