### ISSUE TITLE
Persistent intended destination on SSO login failure

### ISSUE THREAD

**Issue by atoff** [VATSIM-UK/core#930]
When a user goes to login through one of our web services, they are normally taken to the core login page (especially if they are a staff member). However, consider the following;

Someone goes to login to the helpdesk staff panel. They get taken to core to login. But then they realise they actually want to go CTS. They do not complete the login, and instead, navigate to CTS and click login. They then complete the core login, but are taken back to, in this case, the Helpdesk SCP. (I think this is due to an intended destination/return url session var being assigned when they get taken to core)

When a user is sent to core to authenticate, the intended destination Session value/cookie/whatever is set should be removed if they attempt another login from a different SSO system.

At the moment this is not a major issue, because they can log in with core, and then point their browser to CTS again (at this point, the intended destination value has been removed after the successful authentication)

**Comment by tasosb** [comment]
I just want to note that something similar to this happened to me aswell today. I tried logging into the CTS but an error appeared: "Failed to contact core, try again later", or something similar. When I clicked login again, I was redirected to the Helpdesk instead of the CTS.

**Comment by NFarrington** [comment]
This should be fixed in the current development version after the authentication overhaul.
