### ISSUE TITLE
Setting secondary password on account from command line

### ISSUE THREAD

**Issue by atoff** [VATSIM-UK/core#939]
In the recent auth refactoring, the `setPassword` method has been slightly changed, and now when you run the setPassword method from a non-logged in instance (such as the `php artisan tinker` facility when creating an account for development on a local system etc) you get an error (Trying to get property of non-object). The error is more cosmetic, as the actual setting of the password occurs before the reference to `Auth::user()`

(App/Models/Mship/Account @ Line 985)

**Comment by NFarrington** [comment]
This can be worked around by using the mutator (`$account->password = 'password1234';`), which should be all that's necessary when working from the command line for development purposes.

This should still be fixed (by checking if the user is authenticated) in case the method is used from the command line in the future
