### ISSUE TITLE
Sync Bans With Forum

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#945]
Appears to have been started in /app/Listeners/Sync/PushToForum.php
Updates to accounts passed through /app/Console/Commands/SyncCommunity.php

We need to ensure that when an account is suspended/unsuspended in Core (either as a result of a Local Ban or a Network Suspension) that this is passed through to the forum instantly.

Create onBanCreate and onBanRepeal listeners.

**Comment by CalumTowers** [comment]
Bans should be passed instantly
Repeals should be passed instantly
Unbans as a result of expiry passing can be passed nightly on Cron but we should look to improve in the future

**Comment by NFarrington** [comment]
2a8708231d8b0e4cd14ae67300a7244654d44a48
