### ISSUE TITLE
Instant Ban From TS

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#946]
When a ban is applied on Core (local ban) then we should check the TS for any active connections and apply a short (~30 min) ban to tide over until the "full ban" kicks in.
This will mean suspensions issued on Core for TS misconduct can be dealt with instantly and not continue for 10 mins.

**Comment by NFarrington** [comment]
This should be a kick only, or simply the full ban applied. If the client is only kicked, the daemon will then take action the next time they attempt to connect.

**Comment by CalumTowers** [comment]
I think a kick will probably be the best solution and then let the Deamon pick it up on their next login attempt for the ban.
