### ISSUE TITLE
S1 Email

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#951]
When a Division Member gets upgraded to S1, we should send them an email and let them know about our other training opportunities to progress further.

This can be done when the membership sync with CERT occurs.

Consideration should be made for those members V/T in to us as an S1. They will appear in our Divisional feed but should not get an email.

**Comment by fcooper94** [comment]
Dear [Member Name],

On behalf of VATSIM United Kingdom I want to congratulate you on achieving your S1. Thank you for choosing our Division to complete your ATC Training.

Although your OBS-S1 training process is now complete, there are further training opportunities available. As a division we are offering Manchester/Gatwick Ground & Delivery familiarisation sessions. These sessions are optional for members who wish to further their understanding of Ground and Delivery procedures. 

If you are interested in further mentoring, please submit a ticket to the ATC Training Department.
https://helpdesk.vatsim.uk

Kind Regards,

Fraser Cooper
ATC Training Group Manager (New Controller)
VATSIM United Kingdom

**Comment by a-beard** [comment]
Email should be generic not from particular member (for example, if a new TGNC TGM then this would need changing but could be forgotten).

**Comment by CalumTowers** [comment]
Agree @a-beard but we can use the permission system to establish who is the TGM of TGNC and sign it off from them if you would wish.
