### ISSUE TITLE
Check If User Passed An Exercise

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#964]
Each Flight Training Exercise, once completed, will submit a record to smartcars_pirep which, in turn, has position reports submitted by the client every 15 seconds under smartcars_posreps.
We need to test all of the posreps associated with a PIREP against the exercise criteria to determine whether the PIREP has passed the exercise.

There are a number of factors to test and are as follows...

- Position (based on lat/long).
- Altitude
- Speed

The position of the aircraft will determine what speed and altitude restrictions there are.

Simply, if the user has met all of the position, altitude and speed restrictions, the exercise is considered a pass.

_Note that for now, we do not have the exact lat/long of the "boxes" shown in the attached specs. There is no reason why we cannot start to structure the logic tests and fill in the blanks later._

[FTE-VFR-1.docx](https://github.com/VATSIM-UK/core/files/1143127/FTE-VFR-1.docx)
[FTE-VFR-2.docx](https://github.com/VATSIM-UK/core/files/1143125/FTE-VFR-2.docx)
[FTE-VFR-3.docx](https://github.com/VATSIM-UK/core/files/1143126/FTE-VFR-3.docx)

**Comment by danielcrookes1999** [comment]
I have updated FTE-VFR-1 with the Lat/Long. 

[FTE-VFR-1.docx](https://github.com/VATSIM-UK/core/files/1553262/FTE-VFR-1.docx)

**Comment by CalumTowers** [comment]
@NFarrington See above
