### ISSUE TITLE
Allow Users To Book An FTE

### ISSUE THREAD

**Issue by CalumTowers** [VATSIM-UK/core#965]
As a user, I can access a page that displays all available FTEs (as per smartcars_flight) and "book" a flight (adds a record in smartcars_bid against the flight and user selected).

This should then redirect to the FTE specific page (issue #966)

**Comment by NFarrington** [comment]
@CalumTowers In the current views, an image is included for each FTE. Is it intended for every FTE to have an image associated with it, or only "featured" FTEs that will only appear on the dashboard / featured positions?

**Comment by CalumTowers** [comment]
All FTEs will have an image in the same format as is currently shown. On launch, there will be just the three exercises already there
